# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homeless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('handicapped', models.BooleanField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='simpleneed',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mood'),
        ),
        migrations.AddField(
            model_name='simpleneed',
            name='needs',
            field=models.ManyToManyField(to='core.Need'),
        ),
    ]
