# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='simpleneed',
            name='comment',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='simpleneed',
            name='handicapped',
            field=models.BooleanField(default=False),
        ),
    ]
