# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161005_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
