"""
Django settings for simpleneed project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1234567890azertyuiopoiuytreza0987654321'

"""Private settings."""
HOST = 'http://localhost:8000'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rmm^=v#)rd8f%9yqqhjlfxf-kun14ouv!%ti+(1p31+yhd64s-'

# CAPTCHA
reCAPTCHA_SECRET_KEY = '6Ld9dA4UAAAAAOG_0LYDL3Mq1kHenFZggOsZziv5'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'ib3j0f@gmail.com'
EMAIL_HOST_PASSWORD = 'Wyl4p3@1g00gl3'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
