# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:08
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('website', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocatedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.TextField(blank=True, default=b'')),
                ('startts', models.FloatField(blank=True, default=time.time)),
                ('endts', models.FloatField(blank=True, default=core.models.add8hours)),
                ('people', models.IntegerField(blank=True, default=1)),
                ('pwd', models.CharField(blank=True, default=b'', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ts', models.FloatField(blank=True, default=time.time)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('ts', models.IntegerField(default=core.models.currentdatets, primary_key=True, serialize=False)),
                ('needs', models.IntegerField(default=0)),
                ('answeredneeds', models.IntegerField(default=0)),
                ('roams', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NeedLocation',
            fields=[
                ('emergency', models.BooleanField(default=False)),
                ('base', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rneedlocation', serialize=False, to='core.LocatedElement')),
                ('needs', models.ManyToManyField(blank=True, default=[], to='core.Need')),
            ],
            bases=('core.locatedelement',),
        ),
        migrations.CreateModel(
            name='Roam',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('base', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='rroam', serialize=False, to='core.LocatedElement')),
            ],
            bases=('core.locatedelement',),
        ),
        migrations.AddField(
            model_name='message',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.LocatedElement'),
        ),
        migrations.AddField(
            model_name='follower',
            name='follow',
            field=models.ManyToManyField(to='core.LocatedElement'),
        ),
        migrations.AddField(
            model_name='needlocation',
            name='roam',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needlocations', to='core.Roam'),
        ),
    ]
