# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('website', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homeless',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('comment', models.CharField(default=None, max_length=256)),
                ('handicapped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='homeless',
            name='answeredneeds',
            field=models.ManyToManyField(related_name='answered', to='core.Need'),
        ),
        migrations.AddField(
            model_name='homeless',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gender'),
        ),
        migrations.AddField(
            model_name='homeless',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mood'),
        ),
        migrations.AddField(
            model_name='homeless',
            name='needs',
            field=models.ManyToManyField(to='core.Need'),
        ),
    ]
