# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homeless_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeless',
            name='answeredneeds',
            field=models.ManyToManyField(default=[], related_name='answered', to='core.Need'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='comment',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='gender',
            field=models.ForeignKey(default=b'other', on_delete=django.db.models.deletion.CASCADE, to='core.Gender'),
        ),
        migrations.AlterField(
            model_name='homeless',
            name='mood',
            field=models.ForeignKey(default=b'neutral', on_delete=django.db.models.deletion.CASCADE, to='core.Mood'),
        ),
    ]
